name       : html-xml-utils
version    : 7.1
release    : 1
source     :
    - https://www.w3.org/Tools/HTML-XML-utils/html-xml-utils-7.1.tar.gz : ec0efd2263b864bb7e0ae5c59f02c43c5d8aebd0e1c0d2bfce391e665766d56e
license    : W3C
component  : programming.tools
summary    : A number of simple utilities for manipulating HTML and XML files
description: |
    A number of simple utilities for manipulating HTML and XML files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
